version: "3.4"

services:
  app:
    image: node:9.10
    command: bash -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3000:3000
    environment:
      GITLAB_BASE_URL: https://gitlab.com/api/v4
      GITLAB_WEBHOOK_SECRET_TOKEN_KEY: gitlab-webhook-secret
      GITLAB_SECRET_TOKEN_KEY: gitlab-token
      SSH_KEY_VOLUME_SOURCE: $HOME/.ssh
      SSH_KEY_VOLUME_DESTINATION: /ssh-key
      SSH_KEY_FILE_PATH: /ssh-key/id_rsa
    secrets:
      - gitlab-token
      - gitlab-webhook-secret-token-key
secrets:
  gitlab-token:
    file: ./gitlab-token.txt
  gitlab-webhook-secret:
    file: ./gitlab-webhook-secret.txt
